FROM node:21-slim
WORKDIR /app
RUN apt-get update && apt-get install -y \
    openssl \
    libssl3 && \
    rm -rf /var/lib/apt/lists/*

COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build
EXPOSE 3000
CMD ["node", "dist/app.js"]